In [1]:
import sys
sys.path.append("../../src")

In [2]:
import gaussian_systems.conventions as cvn
import numpy as np
from scipy.linalg import issymmetric

In [5]:
random_matrix = np.random.rand(6,6)
issymmetric(random_matrix)

False

In [8]:
symmetrized_matrix = cvn.symmetrize_matrix(random_matrix)
symmetrized_matrix

array([[0.7645562 , 0.55073604, 0.47762268, 0.29697465, 0.44246825,
        0.34725935],
       [0.55073604, 0.12188679, 0.27637542, 0.47532176, 0.49697913,
        0.53100666],
       [0.47762268, 0.27637542, 0.56177562, 0.23709638, 0.70442661,
        0.70360133],
       [0.29697465, 0.47532176, 0.23709638, 0.69020471, 0.70189148,
        0.70856446],
       [0.44246825, 0.49697913, 0.70442661, 0.70189148, 0.56206269,
        0.61508   ],
       [0.34725935, 0.53100666, 0.70360133, 0.70856446, 0.61508   ,
        0.32990707]])

In [9]:
issymmetric(symmetrized_matrix)

True

For a 4-mode system subsystems 2 and 3 would have indices: $(1,2)$ for $x_2, x_3$ and $(5,6)$ for $p_2, p_3$

The library uses quadrature ordering, so: $x_1, x_2, x_3, x_4, p_1, p_2, p_3, p_4$ represents a 4-mode system

In [13]:
cvn.index_list(4,(2,3)) == (1,2,5,6)

array([ True,  True,  True,  True])

In [14]:
exact_60_rotation = np.array([
    [0.5, -np.sqrt(3)/2],
    [np.sqrt(3)/2, 0.5]
])

In [19]:
np.max(np.abs(cvn.rotation_matrix(np.pi/3) - exact_60_rotation)) < 1e-8

np.True_

In [22]:
exact_one_mode_symplectic = np.array([
    [0,1],
    [-1,0]
])

exact_two_mode_symplectic = np.array([
    [0,0,1,0],
    [0,0,0,1],
    [-1,0,0,0],
    [0,-1,0,0]
])

In [23]:
exact_one_mode_symplectic == cvn.symplectic_matrix(1)

array([[ True,  True],
       [ True,  True]])

In [24]:
exact_two_mode_symplectic == cvn.symplectic_matrix(2)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])